# Generated by Django 3.2.7 on 2021-10-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('prov', models.CharField(max_length=100)),
                ('skor', models.CharField(max_length=2)),
                ('isCovid', models.BooleanField()),
            ],
        ),
    ]
