# Generated by Django 3.2.8 on 2021-10-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motivasi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motivasi',
            name='sender',
        ),
        migrations.AlterField(
            model_name='motivasi',
            name='message',
            field=models.TextField(),
        ),
    ]
