# Generated by Django 3.2.8 on 2021-11-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('provinsi', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=30)),
                ('message', models.TextField(max_length=50)),
            ],
        ),
    ]
