# Generated by Django 3.2.8 on 2021-10-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilihan', models.CharField(choices=[('Masker', 'Masker'), ('Hand Sanitizer', 'Hand Sanitizer'), ('Obat-obatana', 'Obat-obatan'), ('Vitamin', 'Vitamin'), ('Oximetry', 'Oximetry'), ('Thermometer', 'Thermometer'), ('Face Shield', 'Face Shield'), ('Strap Mask', 'Strap Mask')], max_length=300)),
            ],
        ),
    ]
