# Generated by Django 3.2.8 on 2021-10-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='gambar',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barang',
            name='link',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='barang',
            name='pilihan',
            field=models.CharField(choices=[('Masker', 'Masker'), ('Hand Sanitizer', 'Hand Sanitizer'), ('Obat-obatan', 'Obat-obatan'), ('Vitamin', 'Vitamin'), ('Oximetry', 'Oximetry'), ('Thermometer', 'Thermometer'), ('Face Shield', 'Face Shield'), ('Strap Mask', 'Strap Mask')], max_length=300),
        ),
    ]
