# Generated by Django 3.2.8 on 2021-11-01 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211027_1544'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Barang',
        ),
    ]
